name: Fetch and Process Kill Data

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour, on the hour
  workflow_dispatch:

jobs:
  fetch-and-process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run script
        run: npx ts-node src/script.ts

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          git commit -m "Update data.json" -a
          git push
